colorScheme: ocean
defaultAppearance: auto

homepage:
  layout: profile
  showRecent: true

article:
  showDate: true
  showReadingTime: true
  showTags: true

# uncomment when ready
# socialLinks:
#   - icon: github
#     url: https://github.com/enyuanman
#   - icon: linkedin
#     url: https://www.linkedin.com/in/enyuan-zwerver/
